name: agenda_crud
description: Uma nova aplicação Flutter

# Versão do SDK Flutter
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Adicione outras dependências do Flutter aqui
  cupertino_icons: ^1.0.2

  # Firebase e Firestore
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.0

  # GetIt para injeção de dependência
  get_it: ^7.6.0

  # MobX para gerenciamento de estado
  mobx: ^2.1.1+4
  flutter_mobx: ^2.0.6+4

  # url_launcher para abrir URLs
  url_launcher: ^6.1.8

  # sqflite para banco de dados local SQLite
  sqflite: ^2.2.8+1

  # mask_text_input_formatter para formatação de entrada de texto
  mask_text_input_formatter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Adicione outras dependências de desenvolvimento aqui
  build_runner: ^2.3.3
  mobx_codegen: ^2.0.7+4

flutter:
  uses-material-design: true

  # Adicione ativos aqui se necessário
  assets:
    - assets/

  # Adicione fontes aqui se necessário
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700

